// Generated by CoffeeScript 1.7.1
$('.tab-list li a').click(function(){
  $(this).parent().addClass('current').siblings().removeClass('current');
  var index = $('.tab-list li.current').index();  
  if(index === 0){
    $('.about-us').show();
    $('.business').hide();
  }
  else{
    $('.business').show();
    $('.about-us').hide();
  }
});
